/**
 * Creating a sidebar enables you to:
- create an ordered group of docs
- render a sidebar for each doc of that group
- provide next/previous navigation

The sidebars can be generated from the filesystem, or explicitly defined here.

Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mcdSidebar:{
    'Margaret Catter Dev': [
      'Margaret Catter Development/index-mcd',
      'Margaret Catter Development/sources',
      {
        type:'category',
        label:'Neo Cities Chronicles',
        items: [
          'Margaret Catter Development/Tabletop-Roleplaying-Games/NeoCitiesChronicles/MagicalGirlsAndMecha',
          'Margaret Catter Development/Tabletop-Roleplaying-Games/NeoCitiesChronicles/NeoCitiesTTRPG',
          'Margaret Catter Development/Tabletop-Roleplaying-Games/NeoCitiesChronicles/MagicalGirlsMechaRising',
        ]
      },
      {
        type:'category',
        label:"High Metropoly's",
        items: [
        'Margaret Catter Development/Tabletop-Roleplaying-Games/HighMetropolys/HighMetropolys',
        'Margaret Catter Development/Tabletop-Roleplaying-Games/HighMetropolys/AscentofCrystalTower',
        'Margaret Catter Development/Tabletop-Roleplaying-Games/HighMetropolys/The Empire of Unsheathed Knives',
        'Margaret Catter Development/Tabletop-Roleplaying-Games/HighMetropolys/ThoseBroken_BelovedThing',
      ]
      },
      {
        type:'category',
        label:'Visual Novels',
        items: [
          'Margaret Catter Development/Visual-Novels/HurricaneLikeMe',
          'Margaret Catter Development/Visual-Novels/AllTheFacesofDanteHall',
          'Margaret Catter Development/Visual-Novels/LookMa_WeMadeIt',
          'Margaret Catter Development/Visual-Novels/MagicalSpaceAdventures',
        ]
      },
      'Margaret Catter Development/Tabletop-Roleplaying-Games/CheckYesRomeo',
      'Margaret Catter Development/Tabletop-Roleplaying-Games/HotOffThePress',
      'Margaret Catter Development/Tabletop-Roleplaying-Games/MicroGames/index',
  ],
  },
  iaSidebar:{
    'Ionie Annette': [
      'Ionie Annette/PitchesPlease',
      {
        type: 'category',
        label: 'The Galaxy Is Limitless', 
        items: [
          'Ionie Annette/The-Galaxy-is-Limitless/TheGalaxyIsLimitless',
          'Ionie Annette/The-Galaxy-is-Limitless/AKingForMyKingdom',
          'Ionie Annette/The-Galaxy-is-Limitless/ThisOldBlackMagic',
        ]
      },
      'Ionie Annette/ChasingTheBeginningofHappyness',
      'Ionie Annette/TheseKidsWillWearCrowns',
      'Ionie Annette/BurnOutTheSun',
      'Ionie Annette/EightKingdoms',
      'Ionie Annette/ProjectMiaHamm',
    ]
  },
  commmonSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

  // By default, Docusaurus generates a sidebar from the docs folder structure
  /* mySidebar: [
    {
      type: 'autogenerated', 
      dirName: '.',
    },
    // {
    //   type: 'link',
    //   label: 'Ionie-Annette',
    //   href: 'src/pages/Ionie-Annette', 
    // },
  ],
*/
  
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
};*/

export default sidebars;
